<?php
/**
 * This file is part of the {@link http://ontowiki.net OntoWiki} project.
 *
 * @copyright Copyright (c) 2011, {@link http://aksw.org AKSW}
 * @license http://opensource.org/licenses/gpl-license.php GNU General Public License (GPL)
 */

/**
 * footer template
 */
?>
            <!--/div-->
            <nav class="buttonrow">
                <ul class="bigger subcolums">
                    <li class="c75l">
                        <label class="hideme" for="updateExtensionInput">Enter resource URI of your extension here:</label>
                        <input type="text" class="wide prefill" id="updateExtensionInput" title="Enter extension resource URI here"/>
                    </li>
                    <li class="c25r"><div class="button justified" id="updateExtensionButton">Register / Update</a></li>
                </ul>
            </nav>
        </section>
    </header> <!-- /#teaser -->

    <hr class="hideme"/>

    <footer id="footer" class="inverse-link-behaviour">
        <h2 class="hideme">Global site informations</h2>
        <div class="subcolumns">
            <div class="c33l">
                <aside class="subcr">
                    <h3>OntoWiki Resources</h3>
                    <ul>
                        <li><a href="http://ontowiki.net">Homepage: http://ontowiki.net</a></li>
                        <li><a href="http://github.com/AKSW/OntoWiki/issues">Issues: http://github.com/AKSW/OntoWiki/issues</a></li>
                        <li><a href="http://github.com/AKSW/OntoWiki">Github: http://github.com/AKSW/OntoWiki</a></li>
                        <li><a href="http://groups.google.com/group/ontowiki-user">User Group: http://groups.google.com/group/ontowiki-user</a></li>
                        <li><a href="http://ohloh.net/p/ontowiki">Ohloh: http://ohloh.net/p/ontowiki</a></li>
                    </ul>
                </aside>
            </div>
            <div class="c20r">
                <aside class="subcr">
                    <h3>Erfurt Resources</h3>
                    <ul>
                        <li><a href="http://erfurt-framework.org">Homepage</a></li>
                        <li><a href="http://github.com/AKSW/Erfurt">Github</a></li>
                    </ul>
                    <h3>AKSW Resources</h3>
                    <ul>
                        <li><a href="http://aksw.org">Homepage</a></li>
                        <li><a href="http://blog.aksw.org">Blog</a></li>
                        <li><a href="http://github.com/AKSW/">Github</a></li>
                    </ul>
                </aside>
            </div>
        </div>
    </footer> <!-- /#footer -->

</div> <!-- /.page_margins -->

</body>
</html>
