<?php
/**
 * This file is part of the {@link http://ontowiki.net OntoWiki} project.
 *
 * @copyright Copyright (c) 2011, {@link http://aksw.org AKSW}
 * @license http://opensource.org/licenses/gpl-license.php GNU General Public License (GPL)
 */

/**
 * extensions.ontowiki.net layout template
 *
 * the most out template layer
 */

// this is the standard template data
$templateData           = $this->templateData;
?><!doctype html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en"
    xmlns:dc="http://purl.org/dc/terms/"
    xmlns:foaf="http://xmlns.com/foaf/0.1/">
<head>

    <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
    <meta http-equiv="content-language" content="en" />
    <meta http-equiv="content-style-type" content="text/css" />

    <!-- stylesheets -->
    <link rel="stylesheet" type="text/css"
        href="<?php echo $this->baseUri?>/layout/all.dev.css" media="all" />
    <style type="text/css">
        .teaserwidecontent > p
        {
            width: 75%;
        }
        #footer .c33l
        {
            width:46%;
        }
    </style>
    <!-- link rel="shortcut icon" href="./images/favicon.ico" type="image/x-icon" / -->
    <!--[if lte IE 6]><link rel="stylesheet" type="text/css" href="" /><![endif]-->

    <!-- javascript -->
    <script type="text/javascript">
        document.documentElement.className += 'js';
        var siteBase="<?php echo $this->baseUri ?>";
    </script>
    <script src="<?php echo $this->baseUri ?>/libs/headjs/head.min.js" type="text/javascript"></script>
    <script src="<?php echo $this->baseUri ?>/scripts/headjs.settings.js" type="text/javascript"></script>
    
    <!-- script src="" type="text/javascript"></script -->

    <!-- (c)2011 Michael Haschke, Webentwicklung | http://48augen.de/ -->

    <!-- meta name="author" content="@@" / -->
    <!-- meta name="keywords" content="@@" / -->
    <!-- meta name="description" content="@@" / -->
    <!-- meta name="date" content="@@" / -->

    <!-- meta name="robots" content="index,follow" / -->

    <!-- meta http-equiv="cache-control" content="max-age=7" / -->
    <!-- meta name="revisit-after" content="30 days" / -->

    <!-- meta name="google-site-verification" content="" / -->

    <!-- link rel="meta" type="application/rdf+xml" title="" href="" / -->
    <!-- link rel="alternate" type="text/xml" title="" href="" / -->


    <meta name="generator" content="<?php echo $this->generator ?>" />
    <link rel="alternate" type="application/rdf+xml" href="<?php echo $this->resourceUri ?>.rdf" />
    <link rel="pingback" href="<?php echo $this->pingbackUrl ?>" />

    <link
        rel="<?php echo $this->curie('http://xmlns.com/foaf/0.1/primaryTopic') ?>"
        href="<?php echo $this->resourceUri?>" />


    <!-- script type="text/javascript" src="<?php echo $this->themeUrlBase ?>scripts/libraries/jquery.js"></script -->
    <!-- script src="<?php echo $this->baseUri ?>/scripts/ajaxManageExtensions.js" type="text/javascript"></script -->
    <!-- script type="text/javascript" src="<?php echo $this->themeUrlBase ?>scripts/libraries/jquery-ui.js"></script -->
    <!-- script type="text/javascript" src="<?php echo $this->libraryUrlBase ?>RDFauthor/src/rdfauthor.js"></script -->

    <title><?php echo $templateData['title'] ?> &mdash; <?php echo $this->siteConfig['name'] ?></title>

<?php
    // includes the GA header script
    $this->headScriptGoogleAnalytics('UA-241023-8');
    // other head scripts
    $this->headScript();
?>
</head>
<body<?php
    foreach ($this->namespaces as $prefix => $ns): ?><?php echo ' xmlns:' . $prefix . '="' . $ns . '"' ?><?php endforeach; ?>>
    <?php echo $this->partial('extensions/header.phtml', $templateData) ?>
    <?php echo $this->renderx(); ?>
    <?php echo $this->partial('extensions/footer.phtml', $templateData) ?>
</body>
</html>

